version: '3.3'

services:

  web:
    container_name: web
    build:
      context: test_celery/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis_db

  redis_db:
    container_name: redis_db
    image: redis
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - 6379:6379
  
  celery:
    container_name: celery
    build:
      context: test_celery/.
      dockerfile: Dockerfile
    command: celery -A test_celery worker
    restart: always
    depends_on:
      - redis_db

  celery-beat:
    container_name: celery-beat
    build:
      context: test_celery/.
      dockerfile: Dockerfile
    command: celery -A test_celery beat
    restart: always
    depends_on:
      - redis_db

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  redis_data: