version: '3.3'

services:

  web:
    container_name: web
    image: web:latest
    build:
      context: test_celery/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis_db
    ports:
      - 8000:8000

  redis_db:
    container_name: redis_db
    image: redis
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - 6379:6379
  
  celery:
    container_name: celery
    image: web:latest
    command: celery -A test_celery worker
    restart: always
    depends_on:
      - web

  celery-beat:
    container_name: celery-beat
    image: web:latest
    command: celery -A test_celery beat
    restart: always
    depends_on:
      - web

volumes:
  redis_data: